### ISSUE TITLE
Start Stream at specific point of time of mp3 ?

### ISSUE THREAD

**Issue by daslicht** [obastemur/mediaserver#6]
Hi,
is it possible to start the stream at specific point of time in the mp3/

For example we have an mp3 which is 5 hours long, but we want to start a 1 hour ?
possible ?

-> related: https://gist.github.com/dtrce/1204243

**Comment by obastemur** [comment]
IMO this is more likely a client feature. `mediaserver` can stream from any point but client needs to manage and decode that.

**Comment by daslicht** [comment]
OK
