### ISSUE TITLE
Website referenced doesn't exist: http://www.webmaster-toolkit.com/mime-types.shtml

### ISSUE THREAD

**Issue by kurzninja** [obastemur/mediaserver#7]
/libs/exts.js line 10:

`// ref : http://www.webmaster-toolkit.com/mime-types.shtml`

I dunno if this is permanent or not, but it seems like the website www.webmaster-toolkit.com doesn't seem to exist at the moment. I've emailed the webmaster to alert him to this issue in hopes this is a temporary issue.

**Comment by obastemur** [comment]
Just tested. It works
