### ISSUE TITLE
Example doesn't work on Desktop and Mobile Safari

### ISSUE THREAD

**Issue by rickitan** [obastemur/mediaserver#8]
Hi @obastemur first of all thank you for a very useful library!

I'm trying to run the example that is included in the library and it works on all browsers except desktop Safari.

The same problem occurs when I try to stream my own MP3s. I haven't been able to figure out why, have you noticed this before? 

Thank you very much! 

-Ricardo.

**Comment by obastemur** [comment]
@rickitan IIRC It's all about the codec. Desktop Safari needs extra codec installation for ogg support. Similar issues with the codec used for MP3.

See https://developer.mozilla.org/en-US/docs/Web/HTML/Supported_media_formats

**Comment by rickitan** [comment]
@obastemur the weird thing is that I went to w3schools: http://www.w3schools.com/tags/tryit.asp?filename=tryhtml5_audio

The audio on that example does work on Safari. But if I download the mp3 sound and stream it form mediaserver it doesn't work.

**Comment by obastemur** [comment]
@rickitan Thanks for all the details. Fix is on master. Also updated npm `0.1.0` Feel free to open this back if you see the issue is still there.

**Comment by rickitan** [comment]
@obastemur I'll let you know as soon as I try it!   Thank you!! 🎊
